name 'supermarket_register'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures supermarket_register'
long_description 'Installs/Configures supermarket_register'
version '0.1.0'

depends  'selinux',  '~> 0.9'
depends  'firewall', '~> 2.5'
depends 'nginx',    '~> 2.7.6'
